// Generated by train_model.py. Do not edit by hand.
#pragma once
#include <math.h>
#include <string.h>
double sigmoid(double x) {
    if (x < 0.0) {
        double z = exp(x);
        return z / (1.0 + z);
    }
    return 1.0 / (1.0 + exp(-x));
}
void xgboost_predict(double * input, double * output) {
    double var0;
    if (input[0] < 2088.0) {
        if (input[1] < 22.36) {
            var0 = 0.0021973366;
        } else {
            var0 = 0.3885601;
        }
    } else {
        if (input[1] < 25.63) {
            var0 = -0.36497062;
        } else {
            var0 = -0.082740836;
        }
    }
    double var1;
    if (input[0] < 1731.0) {
        if (input[1] < 21.12) {
            var1 = 0.040219486;
        } else {
            var1 = 0.3431339;
        }
    } else {
        if (input[1] < 25.63) {
            var1 = -0.3061333;
        } else {
            var1 = 0.028341135;
        }
    }
    double var2;
    if (input[0] < 2450.0) {
        if (input[1] < 23.68) {
            var2 = -0.01063139;
        } else {
            var2 = 0.29659575;
        }
    } else {
        if (input[1] < 28.24) {
            var2 = -0.2977928;
        } else {
            var2 = -0.04381634;
        }
    }
    double var3;
    if (input[0] < 1364.0) {
        if (input[1] < 19.44) {
            var3 = 0.05869019;
        } else {
            var3 = 0.28938296;
        }
    } else {
        if (input[1] < 25.41) {
            var3 = -0.25082073;
        } else {
            var3 = 0.047481593;
        }
    }
    double var4;
    if (input[0] < 1239.0) {
        if (input[1] < 19.48) {
            var4 = 0.11997827;
        } else {
            var4 = 0.26648113;
        }
    } else {
        if (input[1] < 24.01) {
            var4 = -0.248123;
        } else {
            var4 = 0.021925792;
        }
    }
    double var5;
    if (input[0] < 2450.0) {
        if (input[1] < 23.95) {
            var5 = -0.0041481457;
        } else {
            var5 = 0.24839246;
        }
    } else {
        if (input[1] < 28.24) {
            var5 = -0.2589828;
        } else {
            var5 = -0.0476508;
        }
    }
    double var6;
    if (input[0] < 2599.0) {
        if (input[1] < 25.46) {
            var6 = 0.0023457669;
        } else {
            var6 = 0.25439608;
        }
    } else {
        var6 = -0.23810394;
    }
    double var7;
    if (input[0] < 1239.0) {
        if (input[0] < 803.0) {
            var7 = 0.2653125;
        } else {
            var7 = 0.13459179;
        }
    } else {
        if (input[1] < 24.01) {
            var7 = -0.21846071;
        } else {
            var7 = 0.013007729;
        }
    }
    double var8;
    if (input[0] < 2599.0) {
        if (input[1] < 25.46) {
            var8 = 0.0027614755;
        } else {
            var8 = 0.2344154;
        }
    } else {
        var8 = -0.21994822;
    }
    double var9;
    if (input[0] < 1364.0) {
        if (input[1] < 20.18) {
            var9 = 0.049973916;
        } else {
            var9 = 0.23510137;
        }
    } else {
        if (input[1] < 24.01) {
            var9 = -0.21514837;
        } else {
            var9 = 0.005102865;
        }
    }
    double var10;
    if (input[0] < 2076.0) {
        if (input[1] < 22.36) {
            var10 = -0.010891126;
        } else {
            var10 = 0.21788421;
        }
    } else {
        if (input[1] < 28.26) {
            var10 = -0.1806015;
        } else {
            var10 = 0.062476374;
        }
    }
    double var11;
    if (input[0] < 1164.0) {
        if (input[0] < 803.0) {
            var11 = 0.23877712;
        } else {
            var11 = 0.09666465;
        }
    } else {
        if (input[1] < 22.63) {
            var11 = -0.21396954;
        } else {
            var11 = 0.005662172;
        }
    }
    double var12;
    if (input[0] < 2599.0) {
        if (input[1] < 25.46) {
            var12 = 0.0014189099;
        } else {
            var12 = 0.21657006;
        }
    } else {
        var12 = -0.19643173;
    }
    double var13;
    if (input[0] < 1164.0) {
        if (input[0] < 803.0) {
            var13 = 0.22409785;
        } else {
            var13 = 0.08111229;
        }
    } else {
        if (input[1] < 22.3) {
            var13 = -0.20541096;
        } else {
            var13 = 0.0018982951;
        }
    }
    double var14;
    if (input[0] < 2360.0) {
        if (input[1] < 21.0) {
            var14 = -0.060717832;
        } else {
            var14 = 0.14735775;
        }
    } else {
        if (input[1] < 28.24) {
            var14 = -0.19720009;
        } else {
            var14 = 0.018885415;
        }
    }
    double var15;
    if (input[0] < 1731.0) {
        if (input[1] < 21.12) {
            var15 = -0.00081509695;
        } else {
            var15 = 0.20471738;
        }
    } else {
        if (input[1] < 25.63) {
            var15 = -0.17797759;
        } else {
            var15 = 0.016355816;
        }
    }
    double var16;
    if (input[0] < 2599.0) {
        if (input[1] < 25.46) {
            var16 = -0.0026350578;
        } else {
            var16 = 0.1967753;
        }
    } else {
        var16 = -0.17303252;
    }
    double var17;
    if (input[0] < 1102.0) {
        var17 = 0.17776643;
    } else {
        if (input[1] < 21.0) {
            var17 = -0.22098653;
        } else {
            var17 = -0.0015396535;
        }
    }
    double var18;
    if (input[0] < 803.0) {
        var18 = 0.20138772;
    } else {
        if (input[1] < 21.0) {
            var18 = -0.19030872;
        } else {
            var18 = 0.007301735;
        }
    }
    double var19;
    if (input[0] < 2599.0) {
        if (input[1] < 25.46) {
            var19 = -0.0024599454;
        } else {
            var19 = 0.18327135;
        }
    } else {
        var19 = -0.15929729;
    }
    double var20;
    if (input[0] < 1890.0) {
        if (input[1] < 21.12) {
            var20 = -0.015206597;
        } else {
            var20 = 0.1665817;
        }
    } else {
        if (input[1] < 25.63) {
            var20 = -0.18441822;
        } else {
            var20 = -0.00090786687;
        }
    }
    double var21;
    if (input[0] < 803.0) {
        var21 = 0.18996234;
    } else {
        if (input[1] < 20.63) {
            var21 = -0.18056273;
        } else {
            var21 = 0.0017674573;
        }
    }
    double var22;
    if (input[0] < 2599.0) {
        if (input[1] < 25.46) {
            var22 = -0.0024332097;
        } else {
            var22 = 0.1688212;
        }
    } else {
        var22 = -0.14389926;
    }
    double var23;
    if (input[0] < 1239.0) {
        if (input[1] < 19.78) {
            var23 = 0.02657041;
        } else {
            var23 = 0.18479185;
        }
    } else {
        if (input[1] < 22.81) {
            var23 = -0.179623;
        } else {
            var23 = 0.0054148925;
        }
    }
    double var24;

var24 = sigmoid(

    -0.1228208832210598 +

    (var0 + var1 + var2 + var3 + var4 + var5 +

     var6 + var7 + var8 + var9 + var10 + var11 +

     var12 + var13 + var14 + var15 + var16 + var17 +

     var18 + var19 + var20 + var21 + var22 + var23)

);

output[0] = 1.0 - var24;

output[1] = var24;

}
